### ISSUE TITLE
Strange output when entering an empty VCF file

### ISSUE THREAD

**Issue by kokyriakidis** [sbslee/stargazer#4]
I gave Stargazer an empty VCF file (no SNPs found) and it gave me a genotype file with *1/*1 which is clearly not accurate. This also happened in another gene.

```
ugt1a1	KOSTAS	g	*1	*1	*1	*1	1.0	1.0	2.0	no_sv,no_sv	no_sv	no_sv	-100.0	*1	.	.	.	.	-1	-1	-1	-1
```

The command I used is:

```
[INFO] Command: '/Users/kokyriakidis/stargazer -f wgs hg38 ugt1a1 /Users/kokyriakidis/Desktop/test_folder/KOSTAS/genes/ugt1a1/final_vcf/ugt1a1.vcf.gz /Users/kokyriakidis/Desktop/test_folder/KOSTAS/genes/ugt1a1/stargazer --cg vdr'
```

This is the VCF file I gave it:

[ugt1a1.vcf.zip](https://github.com/sbslee/stargazer/files/5073393/ugt1a1.vcf.zip)

Shouldn't it just create an empty genotype file?

**Comment by sbslee** [comment]
Good question! This is normal behavior of Stargazer. An empty VCF file means the sample is reference homozygous for all sites in the target gene (e.g. UGT1A1). Therefore, if the reference genome (e.g. hg19) is *1, then your sample will also be *1/*1. Of course, if the reference genome has non-WT star allele for a target gene (e.g. CYP2D6 for hg19 is *2), then your sample may not have *1/*1 even though you provide an empty VCF file. Hope this make senses. Closing this for now.
